### PR TITLE
helm s3 plugin

### PR DESCRIPTION
**Pull request by emre141**

### CODE REVIEW

**Comment by koslib** [comment]
As it doesn't seem to be a generic need but a quite specific one, could you maybe abstract it out somehow? An idea would be to accept a list of plugins you need installed, but the basis of it would be *just* helm.

**Comment by emre141** [comment]
It would be added helm diff plugin as well which is mostly common using by helm deployment as a  predeploy stage, Is it possible ?

**Comment by koslib** [comment]
As this is not a generically default need for everyone, feel free to inject plugins via a list or something. 

I'd gladly work on this, but sadly I currently do not have time to implement this feature. It could potentially arrive later this year if you wait for my schedule to clear up a bit.

**Comment by emre141** [comment]
Do I need to change anything else ? Sorry I do not much experience about github action, I guess it may be work `helm diff` and `helm s3` command after installed those plugin ?

**Comment by koslib** [comment]
@emre141 please see this from another perspective: s3 and diff plugins are not used neither useful by all users of this action. So please consider an implementation like this:
```
with_plugins: [ list of plugin urls here]
```

and then inside the entrypoint iterate that list and install plugins mentioned there.

Hope that's more helpful. Also, important to note, it's just an idea. The main scope is to not add too much overhead with unnecessary plugins which are not used from a great percentage of the users.

**Comment by emre141** [comment]
@koslib sorry I did not understood. where should I add `with_plugins: [ list of plugin urls here]` ? Which file should I update vy this change ? Sorry for stupid question but i do not have much knowledge about github action metadata

**Comment by koslib** [comment]
I had imagined it in the `with` section of the workflow definition: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepswith. But again, this is merely just a suggestion :) 

The general idea is to let the users select their own helm plugins (when defining their ga workflow), and iterate on that list of helm plugins and install them in this GA. Makes better sense now?

**Comment by koslib** [comment]
Closing since this got addressed in a generic manner in PR https://github.com/koslib/helm-eks-action/pull/25

**Pull request closed without merging**
