### PR TITLE
fix: updated KUBECTL_VERSION to latest stable

### PR DESCRIPTION
**Pull request by dAverk**
fix for issue #50

### CODE REVIEW

**Comment by dAverk** [comment]
@koslib you pinned kubectl version for better docker cache using?

**Review by koslib — CHANGES_REQUESTED** [review]
LGTM, could you please update the readme version ref as well? I can merge and build a new base image right after.

**Comment by koslib** [comment]
> @koslib you pinned kubectl version for better docker cache using?

Yes exactly. The base image (hosted in Dockerhub) is there for not building it every time a pipeline step runs, instead it's just pulled from the public registry.

**Comment by dAverk** [comment]
Ooh, sorry - forgot to update README too :)
Fixed

**Comment by koslib** [comment]
Published [v1.26.0](https://github.com/koslib/helm-eks-action/releases/tag/v1.26.0) - thanks :)

**Pull request merged**
